language: cpp

compiler:
  - clang
  - gcc
  
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update
  - sudo apt-get install boost1.55
  - if [ "$CXX" == "g++" ]; then sudo apt-get install gcc-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.9; fi
  - if [ "$CXX" == "g++" ]; thensudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20; fi
  - if [ "$CXX" == "g++" ]; thensudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20; fi
  - if [ "$CXX" == "g++" ]; thensudo update-alternatives --config gcc; fi
  - if [ "$CXX" == "g++" ]; thensudo update-alternatives --config g++; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

before_script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j2
  - ctest --output-on-failure

